export const offerListActions = {
  ACTIVE_OFFER_LIST_LOADING: "ACTIVE_OFFER_LIST_LOADING",
  ACTIVE_OFFER_LIST_SUCCESS: "ACTIVE_OFFER_LIST_SUCCESS",
  ACTIVE_OFFER_LIST_FAILURE: "ACTIVE_OFFER_LIST_FAILURE",
  ACTIVE_OFFER_LIST_PAGE_OFFSET: "ACTIVE_OFFER_LIST_PAGE_OFFSET",
  ACTIVE_OFFER_LIST_PAGE_SIZE: "ACTIVE_OFFER_LIST_PAGE_SIZE",

  ARCHIVE_OFFER_LIST_LOADING: "ARCHIVE_OFFER_LIST_LOADING",
  ARCHIVE_OFFER_LIST_SUCCESS: "ARCHIVE_OFFER_LIST_SUCCESS",
  ARCHIVE_OFFER_LIST_FAILURE: "ARCHIVE_OFFER_LIST_FAILURE",
  ARCHIVE_OFFER_LIST_PAGE_OFFSET: "ARCHIVE_OFFER_LIST_PAGE_OFFSET",
  ARCHIVE_OFFER_LIST_PAGE_SIZE: "ARCHIVE_OFFER_LIST_PAGE_SIZE",

  ARCHIVING_OFFER_LOADING: "ARCHIVING_OFFER_LOADING",
  ARCHIVING_OFFER_SUCCESS: "ARCHIVING_OFFER_SUCCESS",
  ARCHIVING_OFFER_FAILURE: "ARCHIVING_OFFER_FAILURE",

  FETCH_OFFER_DETAILS_LOADING: "FETCH_OFFER_DETAILS_LOADING",
  FETCH_OFFER_DETAILS_SUCCESS: "FETCH_OFFER_DETAILS_SUCCESS",
  FETCH_OFFER_DETAILS_FAILURE: "FETCH_OFFER_DETAILS_FAILURE",

  RESET_OFFER_LIST_PAGINATION: "RESET_OFFER_LIST_PAGINATION",
};
