import React from "react";
import { render, fireEvent } from "../../../../helpers/testUtils";
import PropertiesListItem from "../PropertiesListItem";

const properties = [
  {
    internalId: 4200,
    propertyCode: "DEMO_JEEVAN",
    name: "AJSG Hotel ",
    channel: "NEMO_CH_03",
    supplier: "ntp",
    city: "Vienna",
    rating: 0,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: 5,
    highestMargin: 5,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 1,
    hotelName: "AJSG Hotel ",
    key: 0,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [
      {
        lang: "DE",
        shortDescription: null,
        description: "Duch lang ggjjgjgjgjgj",
        name: "AJSG Hotel (DE)",
      },
      {
        lang: "EN",
        shortDescription: null,
        description:
          "Our luxurious Apartment hotel in country style is situated directly in the untouched nature of a side valley of the Vinschgau. At our house you can relax 24 hours a day: Start your day with a hearty breakfast and afterwards enjoy the beautiful nature and the various sport activities we have to offer. Relax in our alpine sauna world or our Panorama swimming pool. In the evening you can choose between three different restaurants in which we serve regional and international specialties.",
        name: "AJSG Hotel ",
      },
    ],
  },
  {
    internalId: 4201,
    propertyCode: "XS_NM_0001",
    name: "Bishop's Lodge",
    channel: "DEMO_INDIA_CH",
    supplier: "ntp",
    city: "Santa Fe",
    rating: 5,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: true,
    lowestMargin: 15,
    highestMargin: 15,
    marketPrice: null,
    images: [],
    latitude: 35.715103,
    longitude: -105.91955,
    sequence: 2,
    hotelName: "Bishop's Lodge",
    key: 1,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [
      {
        lang: "DE",
        shortDescription: null,
        description:
          "Unser Resort ist ein Reiseziel wie kein anderes und bietet gehobene Ranchunterkünfte und endlose Erholungsmöglichkeiten für vier Jahreszeiten. Genießen Sie klare, sonnenverwöhnte Tage und erkunden Sie unsere 450 Hektar großen malerischen Wanderwege vom Reiten, Wandern und Mountainbiken.",
        name: "Bishop's Lodge",
      },
      {
        lang: "EN",
        shortDescription: null,
        description:
          "A destination unlike any other, our resort offers upscale ranch lodging and endless four-season recreation. Enjoy clear, sun-drenched days exploring our 450 acres of scenic trails from horseback riding, hiking and mountain biking.",
        name: "Bishop's Lodge",
      },
    ],
  },
  {
    internalId: 4202,
    propertyCode: "DEMO_TEST001",
    name: "DEMO PRADEEP3",
    channel: "DEMO_OFFERBUILDER",
    supplier: "ntp",
    city: "Vienna",
    rating: 0,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: null,
    highestMargin: null,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 3,
    hotelName: "DEMO PRADEEP3",
    key: 2,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4203,
    propertyCode: "DEMO_SUNIL",
    name: "DEMO_SUNIL",
    channel: "DEMO_OFFERBUILDER",
    supplier: "ntp",
    city: "Vienna",
    rating: 0,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: null,
    highestMargin: null,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 4,
    hotelName: "DEMO_SUNIL",
    key: 3,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [
      {
        lang: "DE",
        shortDescription: null,
        description: "Marketing long description in Deutsh",
        name: "DEMO_SUNIL",
      },
      {
        lang: "EN",
        shortDescription: null,
        description: "Marketing long description in English",
        name: "DEMO_SUNIL",
      },
    ],
  },
  {
    internalId: 4204,
    propertyCode: "DEMO_BANJARE",
    name: "English B&B Hotel",
    channel: "DEMO_OFFERBUILDER",
    supplier: "ntp",
    city: "Vienna",
    rating: 4,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: null,
    highestMargin: null,
    marketPrice: null,
    images: [],
    latitude: 48.2082,
    longitude: 16.3738,
    sequence: 5,
    hotelName: "English B&B Hotel",
    key: 4,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4205,
    propertyCode: "DEMO_GHULE",
    name: "GHULE ROCK MANSION",
    channel: "DEMO_OFFERBUILDER",
    supplier: "ntp",
    city: "Vienna",
    rating: 4,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: 20,
    highestMargin: 20,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 6,
    hotelName: "GHULE ROCK MANSION",
    key: 5,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4206,
    propertyCode: "DEMO_HEERO",
    name: "HEERO Merriott STAR",
    channel: "DEMO_OFFERBUILDER",
    supplier: "ntp",
    city: "Vienna",
    rating: 4,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: 8,
    highestMargin: 8,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 7,
    hotelName: "HEERO Merriott STAR",
    key: 6,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4207,
    propertyCode: "DEMO_PKM_002",
    name: "Hotel Paradise PKM",
    channel: "NEMO_CH_01",
    supplier: "ntp",
    city: "Vienna",
    rating: 5,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: 0,
    highestMargin: 0,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 8,
    hotelName: "Hotel Paradise PKM",
    key: 7,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4208,
    propertyCode: "H000892",
    name: "Hotel Pradeep",
    channel: "KOGNITIV_QA",
    supplier: "ntp",
    city: "Pune",
    rating: 5,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: true,
    lowestMargin: 23,
    highestMargin: 23,
    marketPrice: null,
    images: [],
    latitude: 18.610317,
    longitude: 73.78897,
    sequence: 9,
    hotelName: "Hotel Pradeep",
    key: 8,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4209,
    propertyCode: "DEMO_KM",
    name: "KM Royal Palace",
    channel: "DEMO_OFFERBUILDER",
    supplier: "ntp",
    city: "Vienna",
    rating: 5,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: null,
    highestMargin: null,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 10,
    hotelName: "KM Royal Palace",
    key: 9,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4210,
    propertyCode: "DEMO_PRATIK",
    name: "NICE RESORT PRATIK",
    channel: "NEMO_CH_01",
    supplier: "ntp",
    city: "Vienna",
    rating: 4.5,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: 0,
    highestMargin: 0,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 11,
    hotelName: "NICE RESORT PRATIK",
    key: 10,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4211,
    propertyCode: "DEMO_PRADEEP",
    name: "PRADEEP PARTY MANSION",
    channel: "KOGNITIV_QA",
    supplier: "ntp",
    city: "Vienna",
    rating: 0,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: null,
    highestMargin: null,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 12,
    hotelName: "PRADEEP PARTY MANSION",
    key: 11,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4212,
    propertyCode: "DEMO_PUNJABI",
    name: "PUNJABI COOL HOTEL",
    channel: "DEMO_OFFERBUILDER",
    supplier: "ntp",
    city: "Vienna",
    rating: 0,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: null,
    highestMargin: null,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 13,
    hotelName: "PUNJABI COOL HOTEL",
    key: 12,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4213,
    propertyCode: "DEMO_RAJ",
    name: "RAJ Rock Party House",
    channel: "DEMO_OFFERBUILDER",
    supplier: "ntp",
    city: "Vienna",
    rating: 0,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: null,
    highestMargin: null,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 14,
    hotelName: "RAJ Rock Party House",
    key: 13,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4214,
    propertyCode: "DEMO_PR_1",
    name: "Royal Suite PRA_RV",
    channel: "DEMO_INDIA_CH",
    supplier: "ntp",
    city: "Bangalore",
    rating: 5,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: null,
    highestMargin: null,
    marketPrice: null,
    images: [],
    latitude: 12.970991,
    longitude: 77.6069,
    sequence: 15,
    hotelName: "Royal Suite PRA_RV",
    key: 14,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4215,
    propertyCode: "XS_WY_0001",
    name: "Santa Fe Sage Inn",
    channel: "DEMO_INDIA_CH",
    supplier: "ntp",
    city: "Santa Fe",
    rating: 3,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: 0,
    highestMargin: 15,
    marketPrice: null,
    images: [],
    latitude: 35.67994,
    longitude: -105.94874,
    sequence: 16,
    hotelName: "Santa Fe Sage Inn",
    key: 15,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
  {
    internalId: 4216,
    propertyCode: "DEMO_SWAP_01",
    name: "Swap Paradise Star1",
    channel: "NEMO_CH_02",
    supplier: "ntp",
    city: "Vienna",
    rating: 4,
    ratingProvider: "",
    remainingCapitalPool: 0,
    lcn: false,
    lowestMargin: 5,
    highestMargin: 5,
    marketPrice: null,
    images: [],
    latitude: 48.19912,
    longitude: 16.349869,
    sequence: 17,
    hotelName: "Swap Paradise Star1",
    key: 16,
    isSavedProperty: true,
    marketingImages: [],
    descriptions: [],
  },
];
describe("PropertiesListItem component test", () => {
  test("create PropertiesListItem component snapshot", () => {
    const { container } = render(
      <PropertiesListItem
        row={{ properties }}
        dataTestId="A1-active-offer-item-properties-list"
      />,
      {}
    );

    expect(container.firstChild).toMatchSnapshot();
  });
  test(" PropertiesListItem - no properties message", () => {
    const { getByText } = render(
      <PropertiesListItem
        row={{ properties: [] }}
        dataTestId="A1-active-offer-item-properties-list"
      />,
      {}
    );

    expect(getByText(/No Data/i)).toBeInTheDocument();
  });
  test("PropertiesListItem component - active offers tab -  show more button is visible and click on it and it will show collapse all button", async () => {
    const { getByTestId } = render(
      <PropertiesListItem
        row={{ properties }}
        dataTestId="A1-active-offer-item-properties-list"
      />,
      {}
    );
    // check for show more button in the DOM
    expect(
      getByTestId(
        "A1-active-offer-item-properties-list-show-more"
      ).textContent.trim()
    ).toEqual("And 10 more");
    //click on show more button
    await fireEvent.click(
      getByTestId("A1-active-offer-item-properties-list-show-more")
    );
    // after clicking on show more button collapse all button should be in the DOM
    expect(
      getByTestId("A1-active-offer-item-properties-list-collapse-all")
    ).toBeInTheDocument();
    //click on collapse-all button
    await fireEvent.click(
      getByTestId("A1-active-offer-item-properties-list-collapse-all")
    );
    // after clicking on collapse-all button we should have show more button in the DOM
    expect(
      getByTestId(
        "A1-active-offer-item-properties-list-show-more"
      ).textContent.trim()
    ).toEqual("And 10 more");
  });
});
