export const selectBrandsActions = {
    SEARCH_BRANDS_LOADING: 'SEARCH_BRANDS_LOADING',
    SEARCH_BRANDS_SUCCESS: 'SEARCH_BRANDS_SUCCESS',
    SEARCH_BRANDS_FAILURE: 'SEARCH_BRANDS_FAILURE',

    SEARCH_ADD_BRAND: 'SEARCH_ADD_BRAND',
    SEARCH_UPDATE_BRAND: 'SEARCH_UPDATE_BRAND',
    SEARCH_UPDATE_SUPPLIER: 'SEARCH_UPDATE_SUPPLIER',
    SEARCH_UPDATE_STOREFRONT: 'SEARCH_UPDATE_STOREFRONT',
    SEARCH_UPDATE_CHANNEL: 'SEARCH_UPDATE_CHANNEL',
  }