import moment from "moment";

export const ReduxStoreForPropertySearch = {
  searchparams: {
    latitude: "",
    longitude: "",
    startDate: "05/17/2021",
    endDate: "07/17/2021",
    los: 1,
    onlySupplier: false,
    lcn: false,
    remainingCapitalPool: null,
    pageSize: 10,
    pageOffset: 0,
    suppliers: [],
    brands: [
      {
        id: "idb",
        name: "Internal Demo Brand",
        storefronts: [
          {
            id: "ids",
            name: "Internal Demo Storefront",
            suppliers: [
              {
                id: "ntp",
                name: "NTP",
                channels: [
                  {
                    id: "NEMO_CH_01",
                    name: "NEMO_CH_01",
                  },
                  {
                    id: "NEMO_CH_02",
                    name: "NEMO_CH_02",
                  },
                  {
                    id: "NEMO_CH_04",
                    name: "NEMO_CH_04",
                  },
                  {
                    id: "NEMO_CH_05",
                    name: "NEMO_CH_05",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    city: "",
    dateRange: {
      startDate: moment().format("YYYY-MM-DD"),
      endDate: moment().add(60, "days").format("YYYY-MM-DD"),
    },
    destination: {},
    sortBy: {
      sortOrder: 'ASCENDING',
      sortCriteria: 'NAME'
    }
  },
  searchedproperties: {
    loading: false,
    properties: [
      {
        propertyCode: "DEMO_JEEVAN",
        mainProperty: {
          info: {
            name: "AJSG Hotel",
            description: "Best hotel",
            city: "Wien",
            countryName: "Austria",
            images: [
              "https://res.cloudinary.com/seekda-dev/image/upload/w_1920,h_1080,c_fill,f_auto,fl_lossy,q_auto/development/DEMO_JEEVAN/chambre_double_green_fullsize_ecodef-1140x760.jpg",
            ],
            trustyou: null,
            award: null,
          },
          highestMargin: 11,
          lowestMargin: 11,
          propertyCode: "DEMO_JEEVAN",
          lcn: false,
          remainingCapital: null,
          supplier: "ntp",
          channel: "NEMO_CH_04",
        },
        alternateProperties: [
          {
            info: {
              name: "AJSG Hotel",
              description:
                "Our luxurious Apartment hotel in country style is situated directly in the untouched nature of a side valley of the Vinschgau. At our house you can relax 24 hours a day: Start your day with a hearty breakfast and afterwards enjoy the beautiful nature and the various sport activities we have to offer. Relax in our alpine sauna world or our Panorama swimming pool. In the evening you can choose between three different restaurants in which we serve regional and international specialties.",
              city: "Wien",
              countryName: "Austria",
              images: [
                "https://res.cloudinary.com/seekda-dev/image/upload/w_1920,h_1080,c_fill,f_auto,fl_lossy,q_auto/development/DEMO_JEEVAN/chambre_double_green_fullsize_ecodef-1140x760.jpg",
              ],
              trustyou: null,
              award: null,
            },
            propertyCode: "DEMO_JEEVAN",
            lcn: false,
            remainingCapital: null,
            supplier: "ntp",
            channel: "NEMO_CH_06",
          },
          {
            info: {
              name: "AJSG Hotel",
              description:
                "Our luxurious Apartment hotel in country style is situated directly in the untouched nature of a side valley of the Vinschgau. At our house you can relax 24 hours a day: Start your day with a hearty breakfast and afterwards enjoy the beautiful nature and the various sport activities we have to offer. Relax in our alpine sauna world or our Panorama swimming pool. In the evening you can choose between three different restaurants in which we serve regional and international specialties.",
              city: "Wien",
              countryName: "Austria",
              image: {
                url:
                  "https://res.cloudinary.com/seekda-dev/image/upload/w_375,h_210,c_fill,f_auto,fl_lossy,q_auto/development/DEMO_JEEVAN/chambre_double_green_fullsize_ecodef-1140x760.jpg",
                description: null,
                title: null,
                width: 375,
                height: 210,
                category: "Other",
                size: "XSmall",
                globalPosition: 0,
                categoryCode: null,
              },
              trustyou: null,
              award: null,
            },
            propertyCode: "DEMO_JEEVAN",
            lcn: false,
            remainingCapital: null,
            supplier: "ntp",
            channel: "NEMO_CH_05",
          },
          {
            info: {
              name: "AJSG Hotel",
              description:
                "Our luxurious Apartment hotel in country style is situated directly in the untouched nature of a side valley of the Vinschgau. At our house you can relax 24 hours a day: Start your day with a hearty breakfast and afterwards enjoy the beautiful nature and the various sport activities we have to offer. Relax in our alpine sauna world or our Panorama swimming pool. In the evening you can choose between three different restaurants in which we serve regional and international specialties.",
              city: "Wien",
              countryName: "Austria",
              image: {
                url:
                  "https://res.cloudinary.com/seekda-dev/image/upload/w_375,h_210,c_fill,f_auto,fl_lossy,q_auto/development/DEMO_JEEVAN/chambre_double_green_fullsize_ecodef-1140x760.jpg",
                description: null,
                title: null,
                width: 375,
                height: 210,
                category: "Other",
                size: "XSmall",
                globalPosition: 0,
                categoryCode: null,
              },
              trustyou: null,
              award: null,
            },
            propertyCode: "DEMO_JEEVAN",
            lcn: false,
            remainingCapital: null,
            supplier: "ntp",
            channel: "NEMO_CH_03",
          },
          {
            info: {
              name: "AJSG Hotel",
              description:
                "Our luxurious Apartment hotel in country style is situated directly in the untouched nature of a side valley of the Vinschgau. At our house you can relax 24 hours a day: Start your day with a hearty breakfast and afterwards enjoy the beautiful nature and the various sport activities we have to offer. Relax in our alpine sauna world or our Panorama swimming pool. In the evening you can choose between three different restaurants in which we serve regional and international specialties.",
              city: "Wien",
              countryName: "Austria",
              image: {
                url:
                  "https://res.cloudinary.com/seekda-dev/image/upload/w_375,h_210,c_fill,f_auto,fl_lossy,q_auto/development/DEMO_JEEVAN/chambre_double_green_fullsize_ecodef-1140x760.jpg",
                description: null,
                title: null,
                width: 375,
                height: 210,
                category: "Other",
                size: "XSmall",
                globalPosition: 0,
                categoryCode: null,
              },
              trustyou: null,
              award: null,
            },
            propertyCode: "DEMO_JEEVAN",
            lcn: false,
            remainingCapital: null,
            supplier: "ntp",
            channel: "NEMO_CH_01",
          },
          {
            info: {
              name: "AJSG Hotel",
              description:
                "Our luxurious Apartment hotel in country style is situated directly in the untouched nature of a side valley of the Vinschgau. At our house you can relax 24 hours a day: Start your day with a hearty breakfast and afterwards enjoy the beautiful nature and the various sport activities we have to offer. Relax in our alpine sauna world or our Panorama swimming pool. In the evening you can choose between three different restaurants in which we serve regional and international specialties.",
              city: "Wien",
              countryName: "Austria",
              image: {
                url:
                  "https://res.cloudinary.com/seekda-dev/image/upload/w_375,h_210,c_fill,f_auto,fl_lossy,q_auto/development/DEMO_JEEVAN/chambre_double_green_fullsize_ecodef-1140x760.jpg",
                description: null,
                title: null,
                width: 375,
                height: 210,
                category: "Other",
                size: "XSmall",
                globalPosition: 0,
                categoryCode: null,
              },
              trustyou: null,
              award: null,
            },
            propertyCode: "DEMO_JEEVAN",
            lcn: false,
            remainingCapital: null,
            supplier: "ntp",
            channel: "NEMO_CH_02",
          },
        ],
      },
    ],
    channelinfo: {
      loading: false,
      channels: [
        {
          id: "AT_CORDIAL",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AT_KINDERHOTELS",
          name: "Ihr Bett im Allgäu",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AT_SHH",
          name: null,
          type: "Portal",
          status: "AVAILABLE",
        },
        {
          id: "AT_UAB",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AT_UAB_BOOKABLE",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AT_UAB_REQUEST",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AVC-EE",
          name: "AVC Entitlement Engine",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AVC-EE-Marketing",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AVC-EE-Owners",
          name: "AVC-EE-Owners",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AVC-EE-ThirdParty",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AVC-Florentia",
          name: "AVC Florentia",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AVC-Travily",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "AVC_DEMO",
          name: "Anantara Vacation Club",
          type: "Portal",
          status: "AVAILABLE",
        },
        {
          id: "BOESBY",
          name: "only hotels in boesby",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "BOESBY2",
          name: "new portal",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CA_MERIT_001",
          name: "The Merit Collection",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CA_MERIT_002",
          name: "Travel CUTS",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CH_VS",
          name: "Valais",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CH_VS_SAAS",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CH_VS_SUB2",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CH_VS_ZERMATT",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CH_VS_ZURBRIGG",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CHANNEL_TESTING",
          name: "Super Portal Name",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CheckinLondon",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "CPC_CHANNEL_1",
          name: "Forward Channel",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "Demiholger",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_ADEL_P",
          name: "Demo Portal Adel With Description",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_AVC",
          name: "Anantara Vacation Club",
          type: "Portal",
          status: "AVAILABLE",
        },
        {
          id: "DEMO_BALEARES",
          name: "Demo Baleares",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_CHNL_DIGITAL",
          name: "DEMO Digital Trip Channel",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_EMA",
          name: "Demo Ema Portal",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_INDIA_CH",
          name: "DEMO_INDIA_CH",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_LAPLATAPORTAL",
          name: "DEMO_LAPLATAPORTAL",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_LAUSPORTAL",
          name: "test portal for dhisco",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_MERCHANTS",
          name: null,
          type: "Portal",
          status: "ENABLED",
        },
        {
          id: "DEMO_OFFERBUILDER",
          name: "Demo for Nemo / Offerbuilder",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_PORT_MANUEL",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_PORTAL",
          name: "Demo Portal Testi",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_PORTAL001",
          name: "La Plata Demo Portal 001",
          type: "Portal",
          status: "ENABLED",
        },
        {
          id: "DEMO_PORTAL002",
          name: "Test Portal For net",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_PORTAL_ST",
          name: "Portal Simon Taeuber",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_RATEPOOL",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_SABRE_PORTAL",
          name: "Test protal for Sabre",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_SEEKDA",
          name: "tästpørtål😋",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_STAEUBER",
          name: "Testportal Simon",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_TESTIBERT1",
          name: "Testibert das Testportal",
          type: "Portal",
          status: "ENABLED",
        },
        {
          id: "DEMO_TRANSLATIONPORTAL",
          name: "Demo Portal to check translations",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_TRAVELPLAN",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "DEMO_TST_P1",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "FamilyTraveller",
          name: "FamilyTraveller portal",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "HOTELS_SONTHERHU",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "Iberostar_eVolve",
          name: "Iberostar Portal",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "JMS",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "Merit",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "MICHAEL",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "NEMO_CH_01",
          name: "aa",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "NEMO_CH_02",
          name: "NEMO_CH_02",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "NEMO_CH_03",
          name: "NEMO_CH_03",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "NEMO_CH_04",
          name: "NEMO_CH_04",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "NEMO_CH_05",
          name: "NEMO_CH_05",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "NEMO_CH_06",
          name: "NEMO_CH_06",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "NEWPORTAL",
          name: "new portal",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "OceanHotels",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "PORTAL_DHISCO",
          name: "test portal for dhisco",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "PORTAL_OFFERS",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "PORTAL_SABRE",
          name: "Test protal for Sabre",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "SAMPLE_CHANN",
          name: null,
          type: "Portal",
          status: "AVAILABLE",
        },
        {
          id: "SCHPALACERES",
          name: "Palace Portal",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "SEARCHTEST",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "SMARTREALITY",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "TEST_QA_MOR",
          name: "TEST_QA_MOR",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "TESTIBERT",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "TestReindex1",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "TST",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "UAB_T_INCOM",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "VISITBARBADOS",
          name: "Visitbarbados hotel",
          type: "Portal",
          status: "HIDDEN",
        },
        {
          id: "WORTSCHI",
          name: null,
          type: "Portal",
          status: "HIDDEN",
        },
      ],
    },
    propertycart: {
      cartItems: [
        {
          img:
            "https://res.cloudinary.com/seekda-dev/image/upload/w_375,h_210,c_fill,f_auto,fl_lossy,q_auto/development/DEMO_PRADEEP/prad.jpg",
          propertyCode: "DEMO_PRADEEP",
          lcn: false,
          supplier: "ntp",
          channel: "NEMO_CH_01",
          hotelName: "PRADEEP PARTY MANSION",
          remainingCapital: null,
          city: "Wien",
          country: "Austria",
          rating: "",
          description:
            "Experience award-winning service and sophisticated style at JW Marriott Hotel Vienna. Ideally situated between the airport and Vienna Expressway, our 5-star hotel is an ideal destination for both business travelers and vacationing families. Luxury rooms and suites showcase deluxe bedding and marble bathrooms, as well as high-speed internet, desks with ergonomic chairs and laptop-sized safes. Many accommodations also provide striking views of the Pune cityscape or the nearby mountain. Delightful dining options within the hotel include Italian fare, a vegetarian restaurant and a chic rooftop bar. Challenge yourself to a workout in the fitness center or a swim in the outdoor pool, followed by a treatment at the tranquil Quan Spa. If you're hosting an event in Pune, you can explore our 40,000 square feWe are always looking forward to children in our hotel. In our 120 sqm large playground your children will be supervised by professional trained staff. In the meantime the parents can just chill in our relax garden or in our sauna. Besides we provide a fitness room, an indoor swimming pool with panorama view and a cosmetic studio. In summer we offer guided excursions in the beautiful mountain world starting directly in front of our house and in winter you can explore the surrounding ski area with our guides.et of versatile, sophisticated venue space, including multiple boardrooms and a ballroom that can accommodate 2,000 people. We look forward to making your visit truly remarkable at JW Marriott Hotel Vienna.",
          trustyou: "",
          isParent: true,
          key: "DEMO_PRADEEP-2true",
          alternativeProperties: null,
          children: null,
        },
      ],
    },
    totalMatch: 4,
  },
  propertycart: {
    cartItems: [],
  },
  newoffersettingsparam: {
    offerId: "123",
    status: {
      id: "UNPUBLISHED",
      name: "UNPUBLISHED",
    },
    name: "jeevan",
    brands: [
      {
        id: "cdb",
        name: "Client Demo Brand",
        storefronts: [
          {
            id: "ids",
            name: "Internal Demo Storefront",
            suppliers: [
              {
                id: "ntp",
                name: "NTP",
                channels: [
                  {
                    id: "NEMO_CH_02",
                    name: "NEMO_CH_02",
                  },
                  {
                    id: "NEMO_CH_03",
                    name: "NEMO_CH_03",
                  },
                  {
                    id: "NEMO_CH_04",
                    name: "NEMO_CH_04",
                  },
                  {
                    id: "NEMO_CH_05",
                    name: "NEMO_CH_05",
                  },
                  {
                    id: "NEMO_CH_06",
                    name: "NEMO_CH_06",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  languageinfo: {
    loading: false,
    languages: [
      {
        id: "EN",
        name: "English",
      },
      {
        id: "ES",
        name: "Spanish",
      },
      {
        id: "FR",
        name: "French",
      },

      {
        id: "EL",
        name: "Greek",
      },
      {
        id: "SR",
        name: "Serbian",
      },
      {
        id: "BE",
        name: "Belarusian",
      },
      {
        id: "BG",
        name: "Bulgarian",
      },
      {
        id: "MK",
        name: "Macedonian",
      },
      {
        id: "RU",
        name: "Russian",
      },
      {
        id: "UK",
        name: "Ukrainian",
      },
      {
        id: "IW",
        name: "Hebrew",
      },
      {
        id: "AR",
        name: "Arabic",
      },
      {
        id: "HI",
        name: "Hindi",
      },
      {
        id: "TH",
        name: "Thai",
      },
      {
        id: "ZH",
        name: "Chinese",
      },
      {
        id: "JA",
        name: "Japanese",
      },
      {
        id: "KO",
        name: "Korean",
      },
    ],
  },
  newoffermarketinginfo: {
    loading: false,
    marketingInfo: {
      descriptions: [
        {
          description: "hello",
          shortDescription: "ello",
          termsAndConditions: "llo",
          lang: "EN",
        },
      ],
      images: [
        "https://res.cloudinary.com/seekda-dev/image/upload/v1603359435/offer_builder_dev/gapj1ko3ffeuyhspdmbw.png",
      ],
    },
    selectedLanguages: [
      {
        id: "EN",
        name: "English",
      },
    ],
  },
  channelinfo: {
    loading: false,
    channels: [
      {
        id: "AT_CORDIAL",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AT_KINDERHOTELS",
        name: "Ihr Bett im Allgäu",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AT_SHH",
        name: null,
        type: "Portal",
        status: "AVAILABLE",
      },
      {
        id: "AT_UAB",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AT_UAB_BOOKABLE",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AT_UAB_REQUEST",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AVC-EE",
        name: "AVC Entitlement Engine",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AVC-EE-Marketing",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AVC-EE-Owners",
        name: "AVC-EE-Owners",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AVC-EE-ThirdParty",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AVC-Florentia",
        name: "AVC Florentia",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AVC-Travily",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "AVC_DEMO",
        name: "Anantara Vacation Club",
        type: "Portal",
        status: "AVAILABLE",
      },
      {
        id: "BOESBY",
        name: "only hotels in boesby",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "BOESBY2",
        name: "new portal",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CA_MERIT_001",
        name: "The Merit Collection",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CA_MERIT_002",
        name: "Travel CUTS",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CH_VS",
        name: "Valais",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CH_VS_SAAS",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CH_VS_SUB2",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CH_VS_ZERMATT",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CH_VS_ZURBRIGG",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CHANNEL_TESTING",
        name: "Super Portal Name",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CheckinLondon",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "CPC_CHANNEL_1",
        name: "Forward Channel",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "Demiholger",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_ADEL_P",
        name: "Demo Portal Adel With Description",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_AVC",
        name: "Anantara Vacation Club",
        type: "Portal",
        status: "AVAILABLE",
      },
      {
        id: "DEMO_BALEARES",
        name: "Demo Baleares",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_CHNL_DIGITAL",
        name: "DEMO Digital Trip Channel",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_EMA",
        name: "Demo Ema Portal",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_INDIA_CH",
        name: "DEMO_INDIA_CH",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_LAPLATAPORTAL",
        name: "DEMO_LAPLATAPORTAL",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_LAUSPORTAL",
        name: "test portal for dhisco",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_MERCHANTS",
        name: null,
        type: "Portal",
        status: "ENABLED",
      },
      {
        id: "DEMO_OFFERBUILDER",
        name: "Demo for Nemo / Offerbuilder",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_PORT_MANUEL",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_PORTAL",
        name: "Demo Portal Testi",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_PORTAL001",
        name: "La Plata Demo Portal 001",
        type: "Portal",
        status: "ENABLED",
      },
      {
        id: "DEMO_PORTAL002",
        name: "Test Portal For net",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_PORTAL_ST",
        name: "Portal Simon Taeuber",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_RATEPOOL",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_SABRE_PORTAL",
        name: "Test protal for Sabre",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_SEEKDA",
        name: "tästpørtål😋",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_STAEUBER",
        name: "Testportal Simon",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_TESTIBERT1",
        name: "Testibert das Testportal",
        type: "Portal",
        status: "ENABLED",
      },
      {
        id: "DEMO_TRANSLATIONPORTAL",
        name: "Demo Portal to check translations",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_TRAVELPLAN",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "DEMO_TST_P1",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "FamilyTraveller",
        name: "FamilyTraveller portal",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "HOTELS_SONTHERHU",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "Iberostar_eVolve",
        name: "Iberostar Portal",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "JMS",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "Merit",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "MICHAEL",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "NEMO_CH_01",
        name: "aa",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "NEMO_CH_02",
        name: "NEMO_CH_02",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "NEMO_CH_03",
        name: "NEMO_CH_03",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "NEMO_CH_04",
        name: "NEMO_CH_04",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "NEMO_CH_05",
        name: "NEMO_CH_05",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "NEMO_CH_06",
        name: "NEMO_CH_06",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "NEWPORTAL",
        name: "new portal",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "OceanHotels",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "PORTAL_DHISCO",
        name: "test portal for dhisco",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "PORTAL_OFFERS",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "PORTAL_SABRE",
        name: "Test protal for Sabre",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "SAMPLE_CHANN",
        name: null,
        type: "Portal",
        status: "AVAILABLE",
      },
      {
        id: "SCHPALACERES",
        name: "Palace Portal",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "SEARCHTEST",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "SMARTREALITY",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "TEST_QA_MOR",
        name: "TEST_QA_MOR",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "TESTIBERT",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "TestReindex1",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "TST",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "UAB_T_INCOM",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "VISITBARBADOS",
        name: "Visitbarbados hotel",
        type: "Portal",
        status: "HIDDEN",
      },
      {
        id: "WORTSCHI",
        name: null,
        type: "Portal",
        status: "HIDDEN",
      },
    ],
  },
  offerlist: {
    loading: false,
    offers: [],
  },
  currency: {
    loading: false,
    currencyList: [
      "AED",
      "AFN",
      "ALL",
      "AMD",
      "ANG",
      "AOA",
      "ARS",
      "AUD",
      "AWG",
      "AZN",
      "BAM",
      "BBD",
      "BDT",
      "BGN",
      "BHD",
      "BIF",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BTN",
      "BWP",
      "BYR",
      "BZD",
      "CAD",
      "CDF",
      "CHF",
      "CLF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CUC",
      "CUP",
      "CVE",
      "CZK",
      "DJF",
      "DKK",
      "DOP",
      "DZD",
      "EEK",
      "EGP",
      "ERN",
      "ETB",
      "EUR",
      "FJD",
      "FKP",
      "GBP",
      "GEL",
      "GHS",
      "GIP",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HRK",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "IQD",
      "IRR",
      "ISK",
      "JMD",
      "JOD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KMF",
      "KPW",
      "KRW",
      "KWD",
      "KYD",
      "KZT",
      "LAK",
      "LBP",
      "LKR",
      "LRD",
      "LSL",
      "LTL",
      "LVL",
      "LYD",
      "MAD",
      "MDL",
      "MGA",
      "MKD",
      "MMK",
      "MNT",
      "MOP",
      "MRO",
      "MTL",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PAB",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RUB",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SDG",
      "SEK",
      "SGD",
      "SHP",
      "SLL",
      "SOS",
      "SRD",
      "STD",
      "SVC",
      "SYP",
      "SZL",
      "THB",
      "TJS",
      "TMT",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TWD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "UZS",
      "VEF",
      "VND",
      "VUV",
      "WST",
      "XAF",
      "XCD",
      "XDR",
      "XOF",
      "XPF",
      "XXX",
      "YER",
      "ZAR",
      "ZMW",
      "ZWL",
    ],
    selectedCurrency: "EUR",
  },
  marketprice: {
    loading: false,
    marketPriceData: [],
    includeMarketPrice: true
  }
};
